TykTechnologies/tyk-charts

- components/tyk-gateway/templates/_helpers.tpl
- components/tyk-gateway/templates/deployment-gw-repset.yaml
- components/tyk-gateway/values.yaml
- components/tyk-pump/templates/_helpers.tpl
- components/tyk-pump/templates/deployment-pmp.yaml
- components/tyk-pump/values.yaml
- tyk-oss/values.yaml
> TT-8392 - Allow defining extra envVars, Volumes, VolumeMounts

- CHANGELOG.md
> Update CHANGELOG for the new release

- components/tyk-gateway/README.md
- components/tyk-pump/README.md
- tyk-mdcb-data-plane/README.md
- tyk-oss/README.md
> Readme first release

- components/tyk-gateway/templates/deployment-gw-repset.yaml
- components/tyk-gateway/values.yaml
- components/tyk-pump/templates/deployment-pmp.yaml
- tyk-mdcb-data-plane/values.yaml
> Added support for gateway sharding inside gateway and mdcb

- components/tyk-gateway/values.yaml
https://tyktech.atlassian.net/browse/TT-9212
> [TT-9212] Changed boolean to false to fix tyk-gateway component failing to start

- .github/workflows/run-tests.yaml
- components/tyk-pump/README.md
- components/tyk-pump/templates/deployment-pmp.yaml
- components/tyk-pump/values.yaml
- tyk-mdcb-data-plane/README.md
- tyk-mdcb-data-plane/values.yaml
This PR updates `hybridPump` configuration.
It changes the default values defined in values.yaml files; so, `poolSize` is 5 instead of 30, and `callTimeout`is 10 instead of 30.
Morevoer, if users do not specify these fields in the values.yaml file, corresponding environment variables won't be set and Tyk Pump will pick default values for these configurations. 
As of today, according to [Hybrid Pump Documentation](https://github.com/TykTechnologies/tyk-pump/tree/332f7b61b69527bb3a991de63d796dbdca8cce7e#hybrid-rpc-config), default values for `rpc_pool_size` is 5 and `call_timeout` is 10.
https://tyktech.atlassian.net/browse/TT-9188
> [TT-9188] Make Hybrid Pump configuration optional

- components/tyk-gateway/templates/deployment-gw-repset.yaml
Changed port to the correct value
> Fixed wrong port for TYK_GW_POLICIES_POLICYCONNECTIONSTRING

- components/tyk-dashboard/templates/_helpers.tpl
> [TT-9369] Add missing helper to render extraVolumes in dashboard chart

- README.md
- tyk-single-dc/README.md
Add missing `--devel` flag in tyk-single-dc chart documentation and missing markdown highlighters.
> Add missing flag in tyk-single-dc doc

- .github/workflows/run-tests.yaml
- components/tyk-gateway/templates/deployment-gw-repset.yaml
- tyk-mdcb-data-plane/templates/configmap.yaml
- tyk-mdcb-data-plane/templates/secrets.yaml
- tyk-mdcb-data-plane/templates/tests/mdcb-data-plane-test.yaml
- tyk-mdcb-data-plane/templates/tests/script-configmap.yaml
- tyk-mdcb-data-plane/values.yaml
- tyk-oss/templates/tests/script-configmap.yaml
- tyk-single-dc/scripts/tests/tyk-single-dc-test.sh
- tyk-single-dc/templates/tests/script-configmap.yaml
1. Added fullname in the name of configmap and secrets of tyk-mdcb-data-plane chart
2. Added `"helm.sh/hook": test` annotation in the configmap of tests to avoid it's installation as part of the chart.
3. Fixed smoke tests
[TT-9286](https://tyktech.atlassian.net/browse/TT-9286)
To enable installation of multiple hybrid gateway in single namespace
Successfully installed 2 instance of tyk-mdcb-data-plane in same namespace
[TT-9286]: https://tyktech.atlassian.net/browse/TT-9286?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [TT-9286] Fix secret and configmap name of tyk-mdcb-data-plane

- components/tyk-pump/templates/_helpers.tpl
- components/tyk-pump/templates/deployment-pmp.yaml
Fixed the redis url used in the pump deployment.
[TT-9469](https://tyktech.atlassian.net/browse/TT-9469)
[TT-9469]: https://tyktech.atlassian.net/browse/TT-9469?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [TT-9469] Fixed the redis url in pump deployment

- .github/workflows/run-tests.yaml
- components/tyk-bootstrap/templates/_helpers.tpl
- components/tyk-bootstrap/templates/bootstrap-post-install.yaml
- components/tyk-bootstrap/values.yaml
- components/tyk-dashboard/templates/_helpers.tpl
- components/tyk-dashboard/templates/deployment-dashboard.yaml
- components/tyk-dashboard/templates/secrets.yaml
- components/tyk-dashboard/values.yaml
- components/tyk-gateway/templates/_helpers.tpl
- components/tyk-gateway/templates/deployment-gw-repset.yaml
- components/tyk-gateway/templates/secrets.yaml
- components/tyk-gateway/values.yaml
- components/tyk-pump/templates/_helpers.tpl
- components/tyk-pump/templates/deployment-pmp.yaml
- components/tyk-pump/templates/secrets.yaml
- components/tyk-pump/values.yaml
- tyk-mdcb-data-plane/values.yaml
- tyk-oss/values.yaml
- tyk-single-dc/values.yaml
1. Removed `global.redis.sentinelPass` field.
2. Added `global.redis.passSecret` field to enable setting of redis password via a k8s secret.
3. Added `global.mongo.connectionURLSecret` field to enable setting of mongo connection URL via a secret.
4. Added `global.postgres.connectionString` field to enable setting of postgres connection URL via a k8s secret.
5. Removed `bootstrap.secrets` section from bootstrap chart and referred to the `global.secrets` instead.
[TT-9264](https://tyktech.atlassian.net/browse/TT-9264)
[TT-9264]: https://tyktech.atlassian.net/browse/TT-9264?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [TT-9264] Support setting of database credentials using secret

- components/tyk-bootstrap/README.md
- components/tyk-bootstrap/templates/bootstrap-post-install.yaml
- components/tyk-bootstrap/values.yaml
- components/tyk-dashboard/README.md
- components/tyk-dashboard/values.yaml
- components/tyk-gateway/README.md
- components/tyk-gateway/values.yaml
- components/tyk-pump/README.md
- components/tyk-pump/values.yaml
- tyk-mdcb-data-plane/README.md
- tyk-mdcb-data-plane/values.yaml
- tyk-oss/README.md
- tyk-oss/values.yaml
- tyk-single-dc/README.md
- tyk-single-dc/values.yaml
This PR adds missing `nameOverrides` values in subcharts and umbrella charts.
Also, it updates typos in readmes.
https://tyktech.atlassian.net/browse/TT-9545
> [TT-9545] Add missing nameoverrides

- components/tyk-gateway/templates/deployment-gw-repset.yaml
- tyk-mdcb-data-plane/values.yaml
> TT-9547 Edge gw fix

- components/tyk-gateway/templates/secret-certs.yaml
> Fixed bug that prevented tyk-oss gateway from installing with TLS on

- .github/workflows/run-tests.yaml
- tyk-mdcb-data-plane/scripts/tests/mdcb-data-plane-test.sh
- tyk-mdcb-data-plane/templates/_helpers.tpl
- tyk-mdcb-data-plane/templates/tests/mdcb-data-plane-test.yaml
- tyk-oss/scripts/tests/oss-test.sh
- tyk-oss/templates/_helpers.tpl
- tyk-oss/templates/tests/oss-test.yaml
- tyk-single-dc/scripts/tests/tyk-single-dc-test.sh
- tyk-single-dc/templates/_helpers.tpl
- tyk-single-dc/templates/tests/single-dc-test.yaml
> Update Gateway listen ports in integration tests

- README.md
> Docs update for Enterprise Portal

- components/tyk-dashboard/templates/_helpers.tpl
- components/tyk-dashboard/templates/deployment-dashboard.yaml
- tyk-single-dc/values.yaml
Fix value of `TYK_DB_HOSTCONFIG_GATEWAYHOSTNAME` and `TYK_DB_TYKAPI_HOST` environment variable.
[TT-9743](https://tyktech.atlassian.net/browse/TT-9743)
Validated gateway hostname in Dashboard is set correctly.
[TT-9743]: https://tyktech.atlassian.net/browse/TT-9743?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [TT-9743] fix gateway hostname

- components/tyk-gateway/values.yaml
- tyk-mdcb-data-plane/values.yaml
Set `analyticsConfigType` to empty for tyk-mdcb-data-plane.
[TT-9696](https://tyktech.atlassian.net/browse/TT-9696)
[TT-9696]: https://tyktech.atlassian.net/browse/TT-9696?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [TT-9696] fix analytics config setting

- components/tyk-gateway/templates/deployment-gw-repset.yaml
- components/tyk-gateway/values.yaml
- tyk-mdcb-data-plane/values.yaml
- tyk-oss/values.yaml
- tyk-single-dc/values.yaml
```
Change adds flag to enable or disable analytics sending for Hybrid Gateway.
```
With current hybrid helm chart implementation, if you don't want to use Pump to send
analytics and if you disable Pump in value, analytics on hybrid gateway are disabled. 
This change enable you to specifically turn analytics on hybrid gateway on or off.
> TT-9934 Add flag for hybrid analytics enable or disable

- components/tyk-bootstrap/templates/bootstrap-post-install.yaml
- components/tyk-bootstrap/templates/bootstrap-pre-install.yaml
- components/tyk-bootstrap/templates/bootstrap-role-binding.yml
- components/tyk-bootstrap/templates/bootstrap-role.yml
- components/tyk-bootstrap/templates/bootstrap-serviceaccount.yml
- components/tyk-bootstrap/values.yaml
This PR adds a pre-install hook in bootstrapping chart to validate Dashboard licenses.
If dashboard license is not validated, the installation will fail and dashboard installation won't start.
https://tyktech.atlassian.net/browse/TT-5906
> [TT-5906] Add a pre-hook to validate Dashboard license

- components/tyk-pump/templates/deployment-pmp.yaml
Fixes #120
Use the actual property specified in values.yaml
#120
#120
> TT-10136 fix: Use the resources specified in values.yaml

- components/tyk-pump/templates/deployment-pmp.yaml
- components/tyk-pump/values.yaml
See #117 
#117 
https://tyktech.atlassian.net/browse/TT-9703
See #117
> [TT-9703] feat: Add postgres-aggregate backend option to store only aggregate data

- components/tyk-dashboard/values.yaml
- components/tyk-enterprise-portal/values.yaml
- components/tyk-gateway/values.yaml
- components/tyk-pump/values.yaml
- tyk-mdcb-data-plane/values.yaml
- tyk-oss/values.yaml
- tyk-single-dc/values.yaml
This PR updates the image tag to the newest tags for each component & umbrella chart.
https://tyktech.atlassian.net/browse/TT-10143
> [TT-10143] Update image tag to latest ones

- components/tyk-bootstrap/templates/bootstrap-post-install.yaml
- components/tyk-bootstrap/templates/bootstrap-pre-delete.yaml
- components/tyk-bootstrap/templates/bootstrap-pre-install.yaml
- components/tyk-bootstrap/values.yaml
- tyk-single-dc/values.yaml
This PR allows bootstrap images to be configurable. Previously, there was no way to configure image repos or tags for bootstrapping components, see https://github.com/TykTechnologies/tyk-helm-chart/issues/290
https://tyktech.atlassian.net/browse/TT-9631
> [TT-9631] - Make tyk-bootstrap image repository information configurable

- tyk-single-dc/values.yaml
Add a comment in values.yaml to guide users how to configure postgres connectionString via secret.
> keep optional connectionStringSecret field in global.postgres

- components/tyk-dashboard/values.yaml
- components/tyk-gateway/values.yaml
- tyk-data-plane/values.yaml
- tyk-oss/values.yaml
- tyk-stack/values.yaml
Update gateway and dashboard version to v5.2.1 in all the charts
[TT-10135](https://tyktech.atlassian.net/browse/TT-10135)
[TT-10135]: https://tyktech.atlassian.net/browse/TT-10135?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [TT-10135]Update  gateway and dashboard version

- tyk-oss/README.md
> Update tyk-oss README.md

- components/tyk-dashboard/README.md
> Update tyk-dashboard README.md

- tyk-stack/templates/NOTES.txt
> Update NOTES.txt of tyk-stack

- components/tyk-dashboard/values.yaml
- components/tyk-gateway/templates/_helpers.tpl
- components/tyk-gateway/templates/deployment-gw-repset.yaml
- tyk-stack/values.yaml
This PR addresses duplicated environment variables in charts
- TYK_DB_HOSTCONFIG_GATEWAYHOSTNAME
- TYK_GW_SECRET
To resolve duplicated `TYK_GW_SECRET`, just deleted the extra environment variable assignment in tyk-stack chart's default values.yaml since this secret is already created in tyk-gateway component as well.
To resolve duplication in `TYK_DB_HOSTCONFIG_GATEWAYHOSTNAME`, I replaced the value of `dashboard.overrideHostname`, which was wrong in anyways, with `gwHostName` yaml anchor.
https://tyktech.atlassian.net/browse/TT-9322
> [TT-9322] Fix Duplicated Environment Variables

- components/tyk-bootstrap/templates/_helpers.tpl
This pr adds missing template renderer in tyk-bootstrap
> (fix): add missing template renderer in tyk-bootstrap

- components/tyk-gateway/templates/deployment-gw-repset.yaml
Added required changes that set TYK_GW_DBAPPCONFOPTIONS_CONNECTIONSTRING and TYK_GW_POLICIES_POLICYCONNECTIONSTRING only if dashboard is enabled; furthermore set TYK_GW_POLICIES_POLICYSOURCE to "service" if the dashboard component is enabled
> TT-10509, Fix gateway environment settings

- tyk-stack/templates/secrets.yaml
- tyk-stack/templates/tests/stack-test.yaml
This PR updates the hardcoded tyk-stack name; so that it is dynamic 
https://tyktech.atlassian.net/browse/TT-10502
> [TT-10502] rename hardcoded tyk-stack secret

- components/tyk-dev-portal/templates/_helpers.tpl
- components/tyk-dev-portal/templates/statefulset-enterprise-portal.yaml
Set Dashboard URL in Portal using service discovery
[TT-10575](https://tyktech.atlassian.net/browse/TT-10575)
[TT-10575]: https://tyktech.atlassian.net/browse/TT-10575?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [TT-10575] Set Dashboard URL in Portal using service discovery

- components/tyk-dev-portal/templates/secret.yaml
- components/tyk-dev-portal/templates/statefulset-enterprise-portal.yaml
- components/tyk-dev-portal/values.yaml
- tyk-stack/values.yaml
Moved out database configuration from storage section of Dev Portal values file.
[TT-10395](https://tyktech.atlassian.net/browse/TT-10395)
[TT-10395]: https://tyktech.atlassian.net/browse/TT-10395?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [TT-10395] fix portal config

- components/tyk-bootstrap/values.yaml
- tyk-stack/values.yaml
This PR updates beta version of tyk-k8s-bootstrap applications to GA
> Bump tyk-k8s-bootstrap versions to GA

- components/tyk-dev-portal/templates/secret.yaml
- components/tyk-dev-portal/templates/statefulset-enterprise-portal.yaml
- components/tyk-dev-portal/values.yaml
- tyk-stack/values.yaml
Added `useSecretName` field in tyk-dev-portal using which user can set sensitive configuration via k8s secret.
Secret can have following data:
- DevPortalLicense - Sets LicenseKey for Developer Portal
- DevPortalStorageConnectionString - Sets connectionString for Developer Portal
- DevPortalAwsAccessKeyId - Sets AWS S3 Access Key ID
- DevPortalAwsSecretAccessKey - Sets AWS S3 Secret Access Key
[TT-10568](https://tyktech.atlassian.net/browse/TT-10586)
[TT-10568]: https://tyktech.atlassian.net/browse/TT-10568?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [TT-10586] Improve secret management for Developer Portal

- .github/workflows/run-tests.yaml
This PR ignores running CI tests for updates in Markdown files.
> (feat): prevent running CI tests for updates in Markdown files

- components/tyk-dev-portal/templates/secret.yaml
- components/tyk-dev-portal/templates/statefulset-enterprise-portal.yaml
- components/tyk-dev-portal/values.yaml
- tyk-stack/values.yaml
Renamed `DevPortalStorageConnectionString` to `DevPortalDatabaseConnectionString`
> EDP: Fix secret Key name

- components/tyk-gateway/values.yaml
- tyk-data-plane/values.yaml
- tyk-oss/values.yaml
- tyk-stack/values.yaml
This PR addresses suggestions to add valid values for OpenTelemetry related fields in Tyk Gateway.
> (docs): add valid values for OpenTelemetry fields

- components/tyk-dev-portal/values.yaml
- tyk-stack/values.yaml
> downgrade portal version to 1.8.0

- tyk-stack/values.yaml
This PR removes the redundant `mongoURL` field in tyk-stack's values.yaml file.
> Remove redundant field in tyk-stack values file

- README.md
This PR updates main README and adds a link for tyk-mdcb chart.
> Update README.md for tyk-mdcb

- components/tyk-gateway/templates/deployment-gw-repset.yaml
- components/tyk-gateway/values.yaml
- components/tyk-mdcb/templates/deployment-mdcb.yaml
- components/tyk-mdcb/values.yaml
- tyk-control-plane/templates/NOTES.txt
- tyk-control-plane/values.yaml
- tyk-data-plane/README.md
- tyk-data-plane/values.yaml
This PR adds Tyk MDCB Synchroniser feature for tyk-control-plane.
Worker gateways still need to be handled manually. Chart updates regarding worker gateways will be handled in another PR.
https://tyktech.atlassian.net/browse/TT-10898
> [TT-10898] - Add Tyk MDCB synchroniser in tyk-control-plane.

- components/tyk-mdcb/templates/deployment-mdcb.yaml
- components/tyk-mdcb/values.yaml
```
change adds support for TLS in mdcb
```
https://tyktech.atlassian.net/browse/TT-10819
> TT-10819: added support for TLS in mdcb

- components/tyk-pump/templates/deployment-pmp.yaml
- components/tyk-pump/values.yaml
- tyk-control-plane/values.yaml
- tyk-data-plane/values.yaml
- tyk-oss/values.yaml
- tyk-stack/values.yaml
This PR adds a few changes:
- Adds the Graph SQL pump if `postgres-pump` or `postgres` is added to the list of  `pump.backend` in the values
- Adds the SQL graph aggregate pump if `postgres` or `postgres-aggregate` is in the list of `pump.backend`
- Adds the Mongo graph pump if `mongo` is in the list of `pump.backend`
- Install tyk-stack with [postgresql](https://github.com/TykTechnologies/tyk-charts/tree/main/tyk-stack#quick-start-with-postgresql)
-  Modify pump, gateway and dashboard image tags manually in cluster to latest release candidates which are v1.9.0-rc1, v5.3alpha11 and v5.3alpha11 respectively
- Create a graphql API on the dashboard that points to trevorblades and run a sample request e.g 
```graphql
{
countries{
code
}
}
```
- Check activity by graph page on the dashboard it …
> [TT-11124, TT-11070]: update tyk-pump with graph pumps

- tyk-data-plane/values.yaml
- tyk-oss/values.yaml
> (fix): remove redundant spaces between annotations

- components/tyk-dashboard/templates/deployment-dashboard.yaml
- components/tyk-dashboard/values.yaml
- components/tyk-gateway/templates/deployment-gw-repset.yaml
- components/tyk-gateway/values.yaml
- components/tyk-mdcb/values.yaml
- tyk-control-plane/values.yaml
- tyk-data-plane/values.yaml
```
Change moves the haskeys value to the global section for Gateway, Dashboard, and MDCB component charts.
```
https://tyktech.atlassian.net/browse/TT-11056
> TT-11056: update global field value as main value

- tyk-control-plane/README.md
- tyk-stack/README.md
```
change updates the keyName value for mongo and postgre in the documentation
```
https://tyktech.atlassian.net/browse/TT-11384
> TT-11384: update keyName value for Postgre and mongo

- components/tyk-gateway/templates/deployment-gw-repset.yaml
- components/tyk-gateway/values.yaml
- tyk-control-plane/values.yaml
- tyk-data-plane/values.yaml
- tyk-oss/values.yaml
- tyk-stack/values.yaml
Like it says on the tin
https://tyktech.atlassian.net/browse/TT-11397
> [TT-11397] Remove leaky bucket from 5.3 release

- components/tyk-bootstrap/templates/bootstrap-post-install.yaml
- components/tyk-bootstrap/templates/bootstrap-pre-delete.yaml
- components/tyk-bootstrap/templates/bootstrap-pre-install.yaml
- components/tyk-bootstrap/templates/bootstrap-role-binding.yml
- components/tyk-bootstrap/templates/bootstrap-serviceaccount.yml
- components/tyk-bootstrap/values.yaml
- components/tyk-dashboard/templates/deployment-dashboard.yaml
- components/tyk-dashboard/values.yaml
- components/tyk-dev-portal/templates/statefulset-enterprise-portal.yaml
- components/tyk-dev-portal/values.yaml
- components/tyk-gateway/templates/deployment-gw-repset.yaml
- components/tyk-gateway/values.yaml
- components/tyk-pump/templates/deployment-pmp.yaml
- components/tyk-pump/values.yaml
```
change makes service account configurable
```
https://tyktech.atlassian.net/browse/TT-10977
> TT-10977: make service account configurable in the charts

- components/tyk-dashboard/templates/deployment-dashboard.yaml
- components/tyk-dashboard/values.yaml
- components/tyk-gateway/templates/deployment-gw-repset.yaml
- components/tyk-gateway/values.yaml
- components/tyk-mdcb/templates/deployment-mdcb.yaml
- components/tyk-mdcb/values.yaml
- components/tyk-pump/templates/deployment-pmp.yaml
- components/tyk-pump/values.yaml
Do not set any default value for new redis fields, as it leads to upgrade failure if user has enabled `global.redis.useSSL` in it's installation.
[TT-11467](https://tyktech.atlassian.net/browse/TT-10821)
[TT-11467]: https://tyktech.atlassian.net/browse/TT-11467?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [TT-11467] Fix default values for component chart

- components/tyk-bootstrap/templates/bootstrap-post-install.yaml
- components/tyk-bootstrap/templates/bootstrap-pre-delete.yaml
- components/tyk-bootstrap/templates/bootstrap-pre-install.yaml
- components/tyk-bootstrap/templates/bootstrap-role-binding.yml
- components/tyk-bootstrap/templates/bootstrap-role.yml
- components/tyk-bootstrap/templates/bootstrap-serviceaccount.yml
- components/tyk-bootstrap/values.yaml
- components/tyk-dashboard/templates/deployment-dashboard.yaml
- components/tyk-dashboard/values.yaml
- components/tyk-dev-portal/templates/statefulset-enterprise-portal.yaml
- components/tyk-dev-portal/values.yaml
- components/tyk-gateway/templates/deployment-gw-repset.yaml
- components/tyk-gateway/values.yaml
- components/tyk-pump/templates/deployment-pmp.yaml
- components/tyk-pump/values.yaml
```
change makes service account configurable
```
https://tyktech.atlassian.net/browse/TT-10977
> TT-10977: make service account configurable in the charts 

- components/tyk-dashboard/templates/service-dash.yaml
- components/tyk-dashboard/values.yaml
- components/tyk-dev-portal/templates/service-enterprise-portal.yaml
- components/tyk-dev-portal/values.yaml
- components/tyk-gateway/templates/service-gw-control.yaml
- components/tyk-gateway/templates/service-gw.yaml
- components/tyk-gateway/values.yaml
- components/tyk-pump/templates/service-pump.yaml
- components/tyk-pump/values.yaml
```
change adds service name to the Service manifest file for Pump and Gateway.
```
https://tyktech.atlassian.net/browse/TT-11339
> TT-11339: add svc name to manifest for Pump and GW

- components/tyk-dashboard/values.yaml
- tyk-control-plane/values.yaml
- tyk-stack/values.yaml
This PR updates comments about deprecation of `dashboard.hashKeys` field of `tyk-dashboard` chart.
> (fix): update comments about deprecation of dashboard.hashKeys

- components/tyk-bootstrap/values.yaml
- tyk-control-plane/values.yaml
- tyk-stack/values.yaml
This PR enables bootstrapping Enterprise Developer Portal by default while using tyk-control-plane chart.
It also updates in-line comments in values.yaml files.
> (fix): enable bootstrapping developer portal in tyk-control-plane

- components/tyk-dashboard/values.yaml
- components/tyk-dev-portal/values.yaml
- components/tyk-gateway/values.yaml
- components/tyk-mdcb/values.yaml
- components/tyk-pump/values.yaml
- tyk-control-plane/values.yaml
- tyk-data-plane/values.yaml
- tyk-oss/values.yaml
- tyk-stack/values.yaml
```
change updates the component chart image version
```
https://tyktech.atlassian.net/browse/TT-11201
> TT-11201: update component chart image tag

- components/tyk-dashboard/values.yaml
- components/tyk-dev-portal/values.yaml
- tyk-control-plane/values.yaml
- tyk-stack/values.yaml
Update comments in values.yaml to be explicit that the admin details will be used for both Dashboard and Dev Portal during bootstrapping
[TT-11731](https://tyktech.atlassian.net/browse/TT-11731)
[TT-11731]: https://tyktech.atlassian.net/browse/TT-11731?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> TT-11731 Update comments in values.yaml

- components/tyk-mdcb/templates/deployment-mdcb.yaml
- components/tyk-mdcb/values.yaml
- components/tyk-pump/README.md
- components/tyk-pump/templates/deployment-pmp.yaml
- components/tyk-pump/values.yaml
- tyk-control-plane/values.yaml
- tyk-data-plane/README.md
- tyk-data-plane/values.yaml
```
change adds support for analytics on MDCB
```
https://tyktech.atlassian.net/browse/TT-10821
> TT-10821: add support for analytics on MDCB

- components/tyk-dashboard/templates/deployment-dashboard.yaml
```
change by-passes semver check when image tag isn't in semver format
```
https://tyktech.atlassian.net/browse/TT-11705
> TT-11705: add by-pass for semver check if tag isn't in semver format

- components/tyk-mdcb/templates/deployment-mdcb.yaml
- components/tyk-mdcb/values.yaml
- components/tyk-pump/templates/deployment-pmp.yaml
- components/tyk-pump/values.yaml
- tyk-control-plane/values.yaml
- tyk-data-plane/values.yaml
- tyk-oss/values.yaml
- tyk-stack/values.yaml
```
change updates redis ssl values
```
https://tyktech.atlassian.net/browse/TT-11898
> TT-11898: change redis ssl values

- components/tyk-bootstrap/templates/bootstrap-post-install.yaml
- components/tyk-bootstrap/templates/bootstrap-pre-delete.yaml
- components/tyk-bootstrap/templates/bootstrap-pre-install.yaml
- components/tyk-bootstrap/values.yaml
- components/tyk-dashboard/templates/deployment-dashboard.yaml
- components/tyk-dashboard/values.yaml
- components/tyk-dev-portal/templates/statefulset-enterprise-portal.yaml
- components/tyk-dev-portal/values.yaml
- components/tyk-gateway/templates/deployment-gw-repset.yaml
- components/tyk-gateway/values.yaml
- components/tyk-pump/templates/deployment-pmp.yaml
- components/tyk-pump/values.yaml
https://tyktech.atlassian.net/browse/TT-11889
```
change adds the ability to configure custom pod labels and annotation to charts
```
> TT-11889: add ability to configure custom pod label and annotation

- tyk-control-plane/templates/NOTES.txt
> Fix missing " in create secret command in NOTES.txt

- tyk-control-plane/values.yaml
This PR removes a field regarding mTLS from TLS section.
> (fix): remove mtls field under tls configurations for tyk-mdcb

- components/tyk-mdcb/templates/ingress.yaml
```
Change fixes MDCB ingress backend name
```
https://tyktech.atlassian.net/browse/TT-12020
> TT-12020: fix mdcb ingress backend bug

- tyk-control-plane/values.yaml
Allow user to enable TIB from tyk-control-plane values.yaml easily
> TT-12033 add tib configuration to tyk-control-plane values.yaml

- components/tyk-dev-portal/values.yaml
- tyk-control-plane/values.yaml
- tyk-stack/values.yaml
```
change updates dev portal image version.
```
https://tyktech.atlassian.net/browse/TT-12035
> TT-12035: updates dev portal image version

- tyk-control-plane/values.yaml
- tyk-data-plane/values.yaml
- tyk-oss/values.yaml
- tyk-stack/values.yaml
```
change adds pod label configuration to umbrella charts
```
https://tyktech.atlassian.net/browse/TT-12023
> TT-12023: add pod label configuration to umbrella charts

- tyk-data-plane/values.yaml
Comment applies only to On-Prem setup.
If you shard, you need a gateway that isn't sharded with which to propagate api events.
> Fix sharding comment in Tyk Data Plane Chart

- components/tyk-dashboard/values.yaml
- components/tyk-dev-portal/values.yaml
- components/tyk-gateway/values.yaml
- components/tyk-mdcb/values.yaml
- components/tyk-pump/values.yaml
- tyk-control-plane/values.yaml
- tyk-data-plane/values.yaml
- tyk-oss/values.yaml
- tyk-stack/values.yaml
Add additional comments for securityContext and containerSecurityContext fields to explain user can add additional security context fields even if it is not present in the provided values.yaml file.
> Added comments for securityContext and containerSecurityContext fields

- components/tyk-mdcb/values.yaml
- tyk-control-plane/values.yaml
```
change disables store analytics per minute
```
https://tyktech.atlassian.net/browse/TT-12050
> TT-12050: disable store analytics per minute

- components/tyk-bootstrap/templates/bootstrap-post-install.yaml
- components/tyk-bootstrap/templates/bootstrap-pre-delete.yaml
This PR fixes relative paths in bootstrap app commands as relative paths cause issues as the base image is updated.
https://tyktech.atlassian.net/browse/TT-12076
> [TT-12076] - (fix): the relative paths in bootstrap application command

- tyk-control-plane/values.yaml
- tyk-stack/values.yaml
```
change updates bootstrap script image tags in umbrella charts.
```
https://tyktech.atlassian.net/browse/TT-12080
> TT-12080: update bootstrap script tags

- .github/workflows/run-tests.yaml
Update tests to use oci registry of bitnami for installing mongo and redis
> Update mongo chart version

- components/tyk-dashboard/templates/deployment-dashboard.yaml
- components/tyk-dashboard/values.yaml
- components/tyk-gateway/templates/deployment-gw-repset.yaml
- components/tyk-gateway/values.yaml
- tyk-control-plane/values.yaml
- tyk-data-plane/values.yaml
- tyk-oss/values.yaml
- tyk-stack/values.yaml
Add optional param to set init container resources. This is helpful if namespace quota is set and resources definition are required.
https://tyktech.atlassian.net/browse/TT-12289
> Add init containers resources param

- components/tyk-bootstrap/values.yaml
- tyk-control-plane/values.yaml
- tyk-stack/values.yaml
> (update): upgrade tyk-k8s-bootstrap version to 2.1.2

- components/tyk-bootstrap/templates/bootstrap-post-install.yaml
- components/tyk-bootstrap/templates/bootstrap-pre-delete.yaml
- components/tyk-dev-portal/templates/job-portal.yaml
- components/tyk-dev-portal/templates/statefulset-enterprise-portal.yaml
- components/tyk-dev-portal/values.yaml
- tyk-control-plane/values.yaml
- tyk-stack/values.yaml
```
change bootstrap portal using api
```
https://tyktech.atlassian.net/browse/TT-12202
> TT-12202: bootstrap portal using api

- components/tyk-dashboard/templates/deployment-dashboard.yaml
- tyk-control-plane/values.yaml
- tyk-data-plane/values.yaml
- tyk-oss/values.yaml
- tyk-stack/values.yaml
- Changed environment variable `TYK_DB_USESHARDEDANALYTICS` to `TYK_DB_USESHARDEDANLAYTICS`
- Set `useShardedAnalytics` to true by default
[TT-11730](https://tyktech.atlassian.net/browse/TT-11730)
[TT-11730]: https://tyktech.atlassian.net/browse/TT-11730?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [TT-11730] Fixed mongo analytics settings

- components/tyk-gateway/templates/deployment-gw-repset.yaml
Remove check for v3 from gateway probes
[TT-12294](https://tyktech.atlassian.net/browse/TT-12294)
[TT-12294]: https://tyktech.atlassian.net/browse/TT-12294?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [TT-12294] Remove check for v3 from gateway probes

- .github/workflows/run-tests.yaml
Update k8s version matrix to latest 5 versions
[TT-11332](https://tyktech.atlassian.net/browse/TT-11332)
[TT-11332]: https://tyktech.atlassian.net/browse/TT-11332?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Update k8s version matrix

- components/tyk-dashboard/values.yaml
- components/tyk-dev-portal/values.yaml
- components/tyk-gateway/values.yaml
- components/tyk-mdcb/values.yaml
- components/tyk-pump/values.yaml
- tyk-control-plane/values.yaml
- tyk-data-plane/values.yaml
- tyk-oss/values.yaml
- tyk-stack/values.yaml
Update component version to latest release.
[TT-12685](https://tyktech.atlassian.net/browse/TT-12685)
[TT-12685]: https://tyktech.atlassian.net/browse/TT-12685?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [TT-12685] Update component version

- components/tyk-dashboard/values.yaml
- components/tyk-gateway/values.yaml
- tyk-control-plane/values.yaml
- tyk-data-plane/values.yaml
- tyk-oss/values.yaml
- tyk-stack/values.yaml
Update gateway and dashboard tag to LTS version
[TT-13157](https://tyktech.atlassian.net/browse/TT-13157)
[TT-13157]: https://tyktech.atlassian.net/browse/TT-13157?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [TT-13157] Update gateway and dashboard tag to LTS version

- components/tyk-dashboard/values.yaml
- components/tyk-gateway/values.yaml
- components/tyk-mdcb/values.yaml
- tyk-control-plane/values.yaml
- tyk-data-plane/values.yaml
- tyk-oss/values.yaml
- tyk-stack/values.yaml
```
change updates helm chart component tags to LTS
```
https://tyktech.atlassian.net/browse/TT-12922
> TT-12922: update helm chart component version

- tyk-data-plane/scripts/tests/data-plane-test.sh
- tyk-data-plane/templates/tests/data-plane-test.yaml
- tyk-data-plane/values.yaml
- tyk-oss/scripts/tests/oss-test.sh
- tyk-oss/templates/tests/oss-test.yaml
- tyk-oss/values.yaml
- tyk-stack/scripts/tests/tyk-stack-test.sh
- tyk-stack/templates/tests/stack-test.yaml
- tyk-stack/values.yaml
> Add more config options

- components/tyk-dashboard/templates/deployment-dashboard.yaml
- components/tyk-dashboard/values.yaml
- tyk-control-plane/values.yaml
- tyk-stack/values.yaml
```
change adds the following to to dashboard env:
TYK_DB_SECURITY_FORBIDADMINVIEWACCESSTOKEN
TYK_DB_SECURITY_FORBIDADMINRESETACCESSTOKEN
```
https://tyktech.atlassian.net/browse/TT-13751
> TT-13751: add forbid security env to dashboard

- components/tyk-pump/templates/deployment-pmp.yaml
- components/tyk-pump/values.yaml
```
change makes provision for nil probes when healthcheck is enabled
```
https://tyktech.atlassian.net/browse/TT-11901
> TT-11901: make provision for nil probes if healthcheck is enabled

- .github/workflows/move_crd_values_to_operator.yaml
- components/tyk-operator/templates/all.yaml
> test move crd

- .github/workflows/move_crd_values_to_operator.yaml
- components/tyk-operator/templates/all.yaml
> test move-crd-values-to-operator 3

- .github/workflows/move_crd_values_to_operator.yaml
- components/tyk-operator/templates/all.yaml
> fourth crd update

- .github/workflows/move_crd_values_to_operator.yaml
- components/tyk-operator/templates/all.yaml
> 5th crd test

- .github/workflows/move_crd_values_to_operator.yaml
- components/tyk-operator/templates/all.yaml
> test crd move 6th

- components/tyk-pump/templates/service-pump.yaml
> [TT-14005] fix pump svc annotation

- components/tyk-dashboard/values.yaml
- tyk-control-plane/values.yaml
- tyk-stack/values.yaml
This PR updates `values.yaml` files to set `true` to `forbidAdminViewAccessToken` and `forbidAdminResetAccessToken` fields. 
See [TT-13760](https://tyktech.atlassian.net/browse/TT-13760) for the details. 
[TT-13760]: https://tyktech.atlassian.net/browse/TT-13760?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [TT-13760]Default secure for Tyk Dashboard admin view

- tyk-control-plane/values.yaml
- tyk-stack/values.yaml
```
change adds containerSecurityContext to tyk-stack and tyk-control-plane values.yaml file.
```
https://tyktech.atlassian.net/browse/TT-14348
> TT-14348: add containerSecurityContext to tyk-stack and tyk-control-plane values

- components/tyk-dashboard/values.yaml
- components/tyk-dev-portal/values.yaml
- components/tyk-gateway/values.yaml
- components/tyk-mdcb/values.yaml
- components/tyk-operator/values.yaml
- components/tyk-pump/values.yaml
- tyk-control-plane/values.yaml
- tyk-data-plane/values.yaml
- tyk-oss/values.yaml
- tyk-stack/values.yaml
```
change updates the version for the following component charts:
- Gateway / Dashboard: 5.3.10
- Operator 1.2
- Pump 1.12.0
- Tib 1.7.0
- MDCB 2.8.0
- Portal 1.13.0
```
https://tyktech.atlassian.net/browse/TT-14266
> TT-14266: update component charts tag version

- components/tyk-dashboard/templates/_helpers.tpl
- components/tyk-dashboard/templates/deployment-dashboard.yaml
- components/tyk-dashboard/templates/secrets.yaml
- components/tyk-dashboard/values.yaml
- components/tyk-gateway/templates/_helpers.tpl
- components/tyk-gateway/templates/deployment-gw-repset.yaml
- components/tyk-gateway/templates/secrets.yaml
- components/tyk-gateway/values.yaml
- components/tyk-mdcb/templates/_helpers.tpl
- components/tyk-mdcb/templates/deployment-mdcb.yaml
- components/tyk-mdcb/templates/secret-mdcb.yaml
- components/tyk-mdcb/values.yaml
- components/tyk-pump/templates/_helpers.tpl
- components/tyk-pump/templates/deployment-pmp.yaml
- components/tyk-pump/templates/secrets.yaml
- components/tyk-pump/values.yaml
- tyk-control-plane/values.yaml
- tyk-data-plane/values.yaml
- tyk-oss/values.yaml
- tyk-stack/values.yaml
Added the configuration handler for Redis sentinel for both Tyk Dashboard and MDCB. Also fixes the secret issue with setting the `sentinel_password`, now they are handled individually. Also resolved the issue where the `sentinel_password` was not working OOTB with the charts.
- [TT-14658: Sentinel Password does not work with Helm Charts](https://tyktech.atlassian.net/browse/TT-14658)
- [TT-15131: Add Redis Sentinel Global Config Handler for Dashboard and MDCB Charts](https://tyktech.atlassian.net/browse/TT-15131)
References [TT-15131 - Add sentinel environment support in the dashboard and mdcb components #409](https://github.com/TykTechnologies/tyk-charts/pull/409)
> [TT-15131 TT-14660] added redis sentinel to db and mdcb and fixed it for other components

- components/tyk-bootstrap/templates/bootstrap-post-install.yaml
This fix makes that the operatorLicense key is needed in the secret if and only if operator is enabled.
> [TT-15477] added operator env var only if operator is enabled

- components/tyk-dashboard/templates/deployment-dashboard.yaml
- components/tyk-mdcb/templates/deployment-mdcb.yaml
This PR is a duplicate of https://github.com/TykTechnologies/tyk-charts/pull/409 that was created in order to pull latest changes from main branch to fix some integration tests.
> TT-15131 - Add sentinel environment support in the dashboard and mdcb components COPY

- components/tyk-dashboard/templates/deployment-dashboard.yaml
- components/tyk-mdcb/templates/deployment-mdcb.yaml
Removed the duplicate configs that were set for sentinel redis password with DB and MDCB.
[TT-14660](https://tyktech.atlassian.net/browse/TT-14660)
[TT-14660]: https://tyktech.atlassian.net/browse/TT-14660?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [TT-14660] removed duplicate sentinel password configs for db and mdcb

- components/tyk-dashboard/values.yaml
- components/tyk-dev-portal/values.yaml
- components/tyk-gateway/values.yaml
- components/tyk-mdcb/values.yaml
- tyk-control-plane/values.yaml
- tyk-data-plane/values.yaml
- tyk-oss/values.yaml
- tyk-stack/values.yaml
Added the latest updates to the gw/dash/mdcb versions.
> [TT-15193] update component charts tag version
